version: '3.8'

services:
  db:
    image: mysql:8.0
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpassword --silent"]
      interval: 20s
      start_period: 60s

  backend:
    image: laravelapp:v1.1
    deploy:
      replicas: 2
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
      APP_ENV: production
    ports:
      - "9200:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 15s
      start_period: 60s

  frontend:
    image: reactapp:v1.1
    deploy:
      replicas: 2
    ports:
      - "3000:80"
    networks:
      - app-network
    healthcheck:
      disable: true

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: overlay
